### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by jeremywickham** [OTGApps/BJCPStyleGuide#18]
When the phone goes to sleep with the app open and I unlock my phone the app crashes. 

iPhone X
iOS 12.1.4

Attached you'll find a crash report, I see where an abort() is called. 

[BJCPStyles-2019-02-17-151143.zip](https://github.com/OTGApps/BJCPStyleGuide/files/2876010/BJCPStyles-2019-02-17-151143.zip)

**Comment by beenafi** [comment]
I’m seeing the same issue since upgrading iOS TO 12.1.4

**Comment by markrickert** [comment]
Thanks for the reports, gentlemen. I'm working on a fix now.

**Comment by markrickert** [comment]
New version released that fixes crashing.

**Comment by beenafi** [comment]
Mucho gracious, seems to be working as expected now. Thanks for fixing.
